// Generated by scripts/generate-zod.ts
// DO NOT EDIT MANUALLY - Changes will be overwritten

import { z } from 'zod';
import {
  // Import Drizzle table instances for schema generation
  applicationStatusEnum
} from '../../src/db/schema.js'; // Adjusted path and added .js extension

import { createSelectSchema, createInsertSchema } from 'drizzle-zod';

export const ApplicationStatusEnumSchema = createSelectSchema(applicationStatusEnum);
